site_name:           Nemo.jl
repo_url:            https://github.com/Nemocas/Nemo.jl
site_description:    Nemo
site_author:         William Hart

theme:               readthedocs

pages:
- Getting Started:              index.md
- About Nemo:                   about.md
- Types in Nemo:                types.md
- Parent object constructors:   constructors.md
- Univariate polynomials:       build/polynomial.md
- Capped relative power series: build/series.md
- Residue rings:                build/residue.md             
- Fraction fields:              build/fraction.md
- Matrices:                     build/matrix.md
- Integers:                     build/integer.md
- Rationals:                    build/rational.md
- Finite fields:                build/finitefield.md
- P-adic fields:                build/padic.md
- Number fields:                build/numberfield.md
- Real balls:                   build/arb.md
- Permutation groups:           build/perm.md

markdown_extensions:
- extra
- tables
- fenced_code
- mdx_math:
    enable_dollar_delimiter: True

docs_dir: '.'

extra_javascript: ['mathjaxhelper.js', 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']
